### ISSUE TITLE
Does not work with Django 2.0

### ISSUE THREAD

**Issue by JanKoppe** [tutorcruncher/django-bootstrap3-datetimepicker#16]
Hey,

while upgrading to Django 2.0 I stumbled upon this error when trying to use this plugin:

```'DateTimePicker' object has no attribute '_format_value'```

**Comment by samuelcolvin** [comment]
we're no long using this library so can't put much time into fixing this, but happy to accept a PR.

**Comment by Crocmagnon** [comment]
Did you move to another library that provides similar features ?

**Comment by Crocmagnon** [comment]
The relevant code has already been written and merged (see #14). Would you be able to publish a release ?
